# Generated by Django 4.0 on 2021-12-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2, verbose_name='Number')),
                ('Status', models.CharField(max_length=40, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='login')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('role', models.CharField(max_length=50, verbose_name='role')),
            ],
        ),
    ]
